default:
  image: python:3.9-bookworm

before_script:
  - apt update
  - apt install -y locales
  - locale-gen "en_GB.UTF-8"
  - mkdir -p ~/.pip
  - echo "$PIP_CONF" > ~/.pip/pip.conf
  - python -m pip install -U pip

stages:
  - test
  - deploy

variables:
  GIT_DEPTH: 0

python:
  stage: test
  script:
    - python -m pip install tox
    - apt-get install git
    - tox -e cov-init,py3,cov-report
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    paths:
      - coverage_html_report
    expire_in: 1 day

regression-tests:
  stage: test
  script:
    - python -m venv env
    - env/bin/pip install -U pip setuptools wheel
    - env/bin/pip install -U dvc dvc-s3
    - env/bin/pip install -r requirements/test.txt
    - env/bin/pip install .
    - env/bin/dvc pull --force
    - PATH="$PWD/env/bin:$PATH" env/bin/pytest --regression-tests -o junit_logging=all --junitxml=regression.xml data
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    paths:
      - regression.xml
      - regression.html
    reports:
      junit: regression.xml
    expire_in: 1 week

deploy_development:
  stage: deploy
  variables:
    # Set to use GSPs private pypi index
    TWINE_USERNAME: "${PRIVATE_PYPI_USERNAME}"
    TWINE_REPOSITORY_URL: "${PRIVATE_PYPI_URL}"
    TWINE_PASSWORD: "${PRIVATE_PYPI_PASSWORD}"
  script:
    - python -m pip install -U twine
    - python setup.py sdist bdist_wheel
    - python -m twine upload dist/*
  only:
    - develop

deploy_production:
  stage: deploy
  variables:
    # Set to use GSPs private pypi index
    # To change to https://pypi.org/:
    # - remove the TWINE_REPOSITORY_URL
    # - change TWINE_USERNAME to __token__ (double underscores)
    # - change TWINE_PASSWORD to the pypi API token
    TWINE_USERNAME: "${PRIVATE_PYPI_USERNAME}"
    TWINE_REPOSITORY_URL: "${PRIVATE_PYPI_URL}"
    TWINE_PASSWORD: "${PRIVATE_PYPI_PASSWORD}"
  script:
    - python -m pip install -U twine
    - python setup.py sdist bdist_wheel
    - python -m twine upload dist/*
  only:
    - main

pages:
  stage: test
  allow_failure: True
  script:
    - cd docs
    - pip install -r requirements.txt
    - ./generate_docs.sh
    - mv _build ../public
  artifacts:
    paths:
      - public
