# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: ["src"]
- repo: https://github.com/pycqa/isort
  rev: 5.6.4
  hooks:
    - id: isort
      args: ["--profile", "black", "src"]
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      verbose: true # show the output, as this will never fail
      types: [python]
      args:
        [
          "--exit-zero", # allow pylint to 'fail' - we just want info
          "--rcfile=.pylintrc", # Link to your config file
          "src",
        ]
